#!/bin/bash
# Generates a random Janitor key and stores it under /variables/janitorKey

reldir=`dirname $0`
cd $reldir
dir=`pwd`

MAIN_DIR=$dir'/..'
VARIABLES_DIR=$MAIN_DIR/variables
JANITOR_KEY=`openssl rand -base64 32`

echo $VARIABLES_DIR

if [ ! -d "$VARIABLES_DIR" ]; then
	mkdir "$VARIABLES_DIR"
fi

echo $JANITOR_KEY > $VARIABLES_DIR/janitorKey
echo "Janitor key generated:"
echo $JANITOR_KEY