#!/bin/bash
# Sets the App name

reldir=`dirname $0`
cd $reldir
dir=`pwd`

MAIN_DIR=$dir'/..'
VARIABLES_DIR=$MAIN_DIR/variables

if [ -z "$1" ]; then
	echo "No App name passed"
	exit 1
fi

echo $1 > $VARIABLES_DIR/appName
echo "App name set: $1"