#!/bin/bash
# Installs a Cherrycake base database

APP_DIR=/var/www/app

if mysql --host=mariadb -u root -e 'use cherrycake'; then
	echo "Cherrycake database already exists."
	exit 0
fi

echo "Installing Cherrycake skeleton database.";

echo 'CREATE DATABASE cherrycake' | mysql --host=mariadb
for filename in \
	janitor.sql \
	locale.sql \
	location.sql \
	session.sql \
	stats.sql \
	systemLog.sql \
	users.sql \
	location-data.sql
do
	cat $APP_DIR/install/database/$filename | mysql --host=mariadb --database=cherrycake
done

echo "Installed Cherrycake skeleton database"