#!/bin/bash
# Installs a Cherrycake base database

APP_DIR=/var/www/app

sleep 3

echo "Installing Cherrycake skeleton database";

echo 'CREATE DATABASE cherrycake' | mysql --host=mariadb
for filename in \
	janitor.sql \
	locale.sql \
	location.sql \
	session.sql \
	stats.sql \
	systemLog.sql \
	users.sql \
	location.sql
do
	cat $APP_DIR/install/database/$filename | mysql --host=mariadb --database=cherrycake
done

echo "Installed Cherrycake skeleton database"
