#!/bin/bash
# Installs a Cherrycake Skeleton source

APP_DIR=/var/www/app

if [ -f $APP_DIR/load.php ]; then
	echo "Cherrycake skeleton is already installed"
	exit 0
fi

echo "Cloning from Cherrycake skeleton repository"
rm -Rf $APP_DIR/*	
git clone https://github.com/tin-cat/cherrycake-skeleton.git $APP_DIR

echo "Cherrycake skeleton installed, app developer mode set"