#!/bin/bash
# Creates setup configuration files

APP_DIR=/var/www/app
VARIABLES_DIR=/variables

if [ ! -f $APP_DIR/LICENSE_Cherrycake ]; then
	echo "Cherrycake skeleton is not installed, couldn't create configuration files"
	exit 1
fi

# Create database configuration file
if [ -f $APP_DIR/config/Database.config.php ]; then
	echo "Database.config.php already exists."
else
	cp $APP_DIR/config/Database.config.php.example $APP_DIR/config/Database.config.php
	sed -i 's/\[replace_with_your_database_host\]/mariadb/g' $APP_DIR/config/Database.config.php
	sed -i 's/\[replace_with_your_database_user\]/root/g' $APP_DIR/config/Database.config.php
	sed -i 's/\[replace_with_your_database_password\]//g' $APP_DIR/config/Database.config.php
	sed -i 's/\[replace_with_your_database_name\]/cherrycake/g' $APP_DIR/config/Database.config.php
	echo "Database configuration file Database.config.php created."
fi

# Create Cache configuration file
if [ -f $APP_DIR/config/Cache.config.php ]; then
	echo "Cache.config.php already exists."
else
	cp $APP_DIR/config/Cache.config.php.example $APP_DIR/config/Cache.config.php
	sed -i 's/\[replace_with_your_redis_host\]/redis/g' $APP_DIR/config/Cache.config.php
	sed -i 's/\[replace_with_your_redis_port\]/6379/g' $APP_DIR/config/Cache.config.php
	echo "Cache configuration file Cache.config.php created."
fi

# Create Janitor configuration file
if [ ! -f $VARIABLES_DIR/janitorKey ]; then
	echo "Janitor key was not generated, couldn't setup configuration for Janitor"
else

	if [ -f $APP_DIR/config/Janitor.config.php ]; then
		rm $APP_DIR/config/Janitor.config.php
	fi

	JANITOR_KEY=`cat $VARIABLES_DIR/janitorKey`
	JANITOR_KEY_ESCAPED=$(echo $JANITOR_KEY | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')

	cp $APP_DIR/config/Janitor.config.php.example $APP_DIR/config/Janitor.config.php
	sed -i 's/\[replace_with_your_janitor_key\]/'$JANITOR_KEY_ESCAPED'/g' $APP_DIR/config/Janitor.config.php
	echo "Janitor configuration file Janitor.config.php created."

fi
