#!/bin/bash
# Installs a Cherrycake skeleton using composer

APP_DIR=/var/www/app

if [ -f $APP_DIR/LICENSE_Cherrycake ]; then
	echo "Cherrycake skeleton is already installed"
	exit 0
fi

composer selfupdate
composer create-project --prefer-dist --stability dev tin-cat/cherrycake-skeleton $APP_DIR
chmod 777 $APP_DIR/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php
