#!/bin/bash
# Sets this Cherrycake installation in app developer mode
# This removes the exposed Cherrycake engine from /cherrycake-engine, and sets back the App to use the cherrycake engine from the composer package

APP_DIR=/var/www/app

if [ ! -f $APP_DIR/load.php.example ]; then
	echo "Cherrycake Skeleton is not installed"
	exit 0
fi

if [ -f $APP_DIR/load.php ]; then
	rm $APP_DIR/load.php
fi

# Set the cherrycake skeleton to use the outher exposed cherrycake engine
cp $APP_DIR/load.php.example $APP_DIR/load.php
sed -i 's/\[replace-with-path-to-cherrycake-engine-load.php\]/vendor\/tin-cat\/cherrycake-engine\/load.php/g' $APP_DIR/load.php
echo "load.php created"

echo "App developer mode set"
echo "App is exposed under /app"